name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /
            rm -rf /var/www/link-shortener/
            rm -rf /home/cloned-repo-link-shortener/
            cd /var/www
            mkdir link-shortener
            cd /home
            mkdir cloned-repo-link-shortener
            cd cloned-repo-link-shortener
            git clone https://github.com/Andrii-Yukhymenko/link-shortener.git
            cd link-shortener/
            yarn install
            yarn build
            cp -r build/* /var/www/link-shortener
